const app=document.getElementById('app');
const stages=[
 {key:'UNDERSTAND',label:'Customer Centricity',title:'UNDERSTAND ME',quote:'“I\'ve already come here twice. Every time someone tells me something different. Honestly, I\'m getting tired of this.”',options:[
  'Don\'t worry, I\'ll get it sorted.','Okay, let me check your phone and bill.','I understand this has been frustrating. Before I suggest the next step, could you tell me what happened during your previous visits?','You\'ll have to speak to the person who handled your case earlier.'
 ],best:2,goodTitle:'YOU CHOSE TO UNDERSTAND.',good:'Rahul hasn\'t just brought you a problem. He\'s brought you an experience that has already left him frustrated. Before deciding what he needs, understand what he\'s been through.',beh:'Listen · Ask · Don\'t assume'},
 {key:'CONNECT',label:'Customer Relation',title:'CONNECT WITH ME',quote:'“Last time I was told to come back today. I came after work, and now I\'m being told something else.”',options:[
  'I understand. Let me see what I can do.','I can understand why you\'d be frustrated after making another trip here. Let me check what happened and see how I can help.','I\'m sorry, but I wasn\'t the person who spoke to you earlier.','Please calm down. I\'ll check.'
 ],best:1,goodTitle:'YOU ACKNOWLEDGED THE PERSON — NOT JUST THE PROBLEM.',good:'A customer can be waiting for a solution and still feel ignored. A premium interaction makes the person feel seen, heard and respected.',beh:'Attention · Respect · Warmth'},
 {key:'HELP',label:'Solution Orientation',title:'HELP ME',quote:'“So you\'re saying nothing can be done today?”',options:[
  'Unfortunately, that\'s the process. You\'ll have to wait.','That option isn\'t available today, but let me check what alternatives we can offer.','I\'ll need to ask my manager.','No, that\'s not possible.'
 ],best:1,goodTitle:'YOU DIDN\'T PROMISE WHAT YOU COULDN\'T DELIVER.',good:'You were transparent about the limitation. But instead of ending the conversation there, you looked for what could be done.',beh:'Possibilities · Alternatives · Clarity'},
 {key:'STAY',label:'Resolution Management',title:'STAY WITH ME',quote:'“Okay. But then I have to explain everything again to someone else?”',options:[
  'Yes, you\'ll have to explain it to the concerned team.','I\'ll tell them what happened.','I understand you don\'t want to repeat everything again. I\'ll brief the concerned team about what we\'ve discussed and make sure you know what happens next.','Let me call my manager.'
 ],best:2,goodTitle:'YOU TOOK OWNERSHIP OF THE EXPERIENCE.',good:'The issue may involve another person or team. That doesn\'t mean the customer should feel like they\'ve been passed around. Resolution includes clear next steps and follow-through.',beh:'Ownership · Follow-through · Next steps'}
];
let current=0,answered=false,selectedCommit='';
function progress(active){return `<div class="stage-head"><div class="progress">${stages.map((s,i)=>`<i class="${i<active?'on':''}"></i>`).join('')}</div><div class="progress-label">${active}/4</div></div>`}
function shell(content,cls=''){app.innerHTML=`<div class="wrap ${cls} fade">${content}</div>`;window.scrollTo({top:0,behavior:'smooth'})}
function opening(){shell(`<section class="hero"><div class="hero-inner"><div class="eyebrow">SALES IMAGE TRANSFORMATION</div><h1>PREMIUM<br>CUSTOMER EXPERIENCE</h1><div class="question">What makes a customer feel truly valued?</div><p class="sub">Not just what you do.<br><strong>How you make them feel while you do it.</strong></p><div class="pillars"><span>DIGNITY</span><span>PATIENCE</span><span>WARMTH</span></div><button class="cta" onclick="situation()">STEP INTO THE EXPERIENCE →</button></div></section>`)}
function visual(){return `<div class="scene-visual"><div class="store-window"></div><div class="store-line"></div><div class="phone"></div><div class="bubble customer-b">“I’ve already been here twice…”</div><div class="person customer"><div class="head"></div><div class="body"></div><div class="arm a"></div><div class="arm b"></div></div><div class="person advisor"><div class="head"></div><div class="body"></div><div class="arm a"></div><div class="arm b"></div></div><div class="bubble advisor-b">YOUR MOVE</div></div>`}
function situation(){shell(`<section class="stage">${progress(0)}<div class="scene"><div>${visual()}</div><div class="content"><div class="section-label">YOUR ROLE</div><h2>You’re the sales advisor.</h2><p class="lead">A customer walks in with a concern. He’s already frustrated.</p><div class="quote">“I’ve already come here twice. Every time someone tells me something different. Honestly, I’m getting tired of this.”</div><button class="cta" onclick="decision(0)">WHAT'S YOUR MOVE? →</button></div></div></section>`)}
function decision(i){current=i;answered=false;const s=stages[i];shell(`<section class="stage">${progress(i)}<div class="scene"><div>${visual()}</div><div class="content"><div class="section-label">${s.label.toUpperCase()}</div><h2>${s.title}</h2><div class="quote">${s.quote}</div><p class="lead">What would you say?</p><div class="options">${s.options.map((o,n)=>`<button class="option" onclick="choose(${n})"><span class="letter">${String.fromCharCode(65+n)}</span><span>${o}</span></button>`).join('')}</div><div id="response"></div></div></div></section>`)}
function choose(n){const s=stages[current],box=document.getElementById('response');if(n===s.best){box.innerHTML=`<div class="response good"><div class="tag">NOTICE THE DIFFERENCE</div><h3>${s.goodTitle}</h3><p>${s.good}</p><div class="tag" style="margin-top:18px">THE MOVE</div><p><strong>${s.key}</strong> · ${s.label}<br>${s.beh}</p><button class="cta next" onclick="next()">CONTINUE →</button></div>`}else{box.innerHTML=`<div class="response look"><div class="tag">LOOK AGAIN</div><h3>Would this help Rahul feel valued?</h3><p>Think about what the customer needs from this moment — not only what needs to be done.</p><button class="cta next" onclick="decision(${current})">TRY AGAIN</button></div>`}}
function next(){if(current<3)decision(current+1);else reveal()}
function reveal(){shell(`<section class="reveal"><div class="section-label">YOU JUST EXPERIENCED PREMIUM SERVICE</div><h2>Four moves.<br>One customer experience.</h2><div class="reveal-grid">${stages.map((s,i)=>`<div class="move"><div class="num">0${i+1}</div><h3>${s.key}</h3><p>${s.label}<br>${s.title.replace(s.key,'').trim()}</p></div>`).join('')}</div><button class="cta" onclick="premium()">SEE THE BIGGER IDEA →</button></section>`)}
function premium(){shell(`<section class="reveal"><div class="section-label">WHAT DOES “VALUED” FEEL LIKE?</div><h2>Premium service isn't about doing more.</h2><p class="lead" style="max-width:650px">It’s about making the customer feel valued while you help them move forward.</p><div class="feelings"><div class="feeling"><h3>DIGNITY</h3><p>I feel respected.</p></div><div class="feeling"><h3>PATIENCE</h3><p>I feel heard.</p></div><div class="feeling"><h3>WARMTH</h3><p>I feel comfortable.</p></div></div><button class="cta" onclick="reflection()">YOUR NEXT CUSTOMER →</button></section>`)}
function reflection(){shell(`<section class="stage"><div class="reflection"><div class="section-label">YOUR NEXT CUSTOMER</div><h2>Which move will you consciously practise?</h2><p class="lead">Choose one behaviour you want to carry into your next customer interaction.</p><div class="choice-grid">${stages.map((s,i)=>`<button class="commit" onclick="commit(${i})"><h3>${s.key}</h3><p>${['I’ll listen before assuming.','I’ll make the customer feel heard.','I’ll look for what can be done.','I’ll take ownership of the next step.'][i]}</p></button>`).join('')}</div><div id="commit"></div></div></section>`)}
function commit(i){selectedCommit=stages[i].key;document.querySelectorAll('.commit').forEach((b,n)=>b.classList.toggle('selected',n===i));document.getElementById('commit').innerHTML=`<div class="response good"><div class="tag">YOUR NEXT MOVE</div><h3>${selectedCommit}</h3><p>One small change can change the entire experience.</p><button class="cta next" onclick="closing()">FINISH EXPERIENCE →</button></div>`}
function closing(){shell(`<section class="close"><div class="eyebrow">SALES IMAGE TRANSFORMATION · PREMIUM CUSTOMER EXPERIENCE</div><h2>MAKE THEM<br>FEEL VALUED.</h2><p>Premium service isn't remembered only by what you did. It’s remembered by how the customer felt.</p><button class="cta" onclick="opening()">RESTART EXPERIENCE</button><div class="small">One interaction can change the entire experience.</div></section>`)}
document.getElementById('restart').addEventListener('click',opening);opening();
