const app=document.getElementById('app');let chosen='';
const d=[
{title:'CUSTOMER CENTRICITY',phrase:'UNDERSTAND ME.',exp:'Put yourself on the customer’s side before deciding what the solution should be.',beh:['Listen','Ask','Don’t assume'],q:'“I’ve already come here twice. Every time someone tells me something different. Honestly, I’m getting tired of this.”',best:'C',a:[['A','“Don’t worry, I’ll get it sorted.”'],['B','“Okay, let me check your phone and bill.”'],['C','“I understand this has been frustrating. Before I suggest the next step, could you tell me what happened during your previous visits?”'],['D','“You’ll have to speak to the person who handled your case earlier.”']]},
{title:'CUSTOMER RELATION',phrase:'CONNECT WITH ME.',exp:'Build comfort and trust through the way you interact—not just through what you say.',beh:['Attention','Respect','Warmth'],q:'“Last time I was told to come back today. I came after work, and now I’m being told something else.”',best:'B',a:[['A','“I understand. Let me see what I can do.”'],['B','“I can understand why you’d be frustrated after making another trip here. Let me check what happened and see how I can help.”'],['C','“I’m sorry, but I wasn’t the person who spoke to you earlier.”'],['D','“Please calm down. I’ll check.”']]},
{title:'SOLUTION ORIENTATION',phrase:'HELP ME.',exp:'A solution-oriented approach doesn’t mean promising something you can’t deliver. It means looking for possibilities within what you can actually do.',beh:['Possibilities','Alternatives','Clarity'],q:'“So you’re saying nothing can be done today?”',best:'B',a:[['A','“Unfortunately, that’s the process. You’ll have to wait.”'],['B','“That option isn’t available today, but let me check what alternatives we can offer.”'],['C','“I’ll need to ask my manager.”'],['D','“No, that’s not possible.”']]},
{title:'RESOLUTION MANAGEMENT',phrase:'STAY WITH ME.',exp:'Resolution isn’t only about finding an answer. It’s about helping the customer understand what happens next—and following through.',beh:['Ownership','Follow-through','Next steps'],q:'“Okay. But then I have to explain everything again to someone else?”',best:'C',a:[['A','“Yes, you’ll have to explain it to the concerned team.”'],['B','“I’ll tell them what happened.”'],['C','“I understand you don’t want to repeat everything again. I’ll brief the concerned team about what we’ve discussed and make sure you know what happens next.”'],['D','“Let me call my manager.”']]}
];
function render(x){app.innerHTML=`<section class="screen">${x}</section>`;scrollTo({top:0,behavior:'smooth'})}function prog(n){return `<div class="progress">${[0,1,2,3].map(i=>`<i class="${i<=n?'on':''}"></i>`).join('')}</div>`}
function opening(){render(`<div class="hero"><div class="eyebrow">SALES IMAGE TRANSFORMATION</div><h1>PREMIUM<br>CUSTOMER<br>EXPERIENCE</h1><p class="hero-copy">It’s not just what you do.<br>It’s how you make the customer feel.</p><div class="triad"><span>DIGNITY</span><span>PATIENCE</span><span>WARMTH</span></div><button class="primary" onclick="situation()">STEP INTO THE EXPERIENCE →</button></div>`)}
function situation(){render(`${prog(0)}<div class="two"><div class="illustration"><div class="person"></div></div><div><div class="kicker">YOUR ROLE</div><h2>Meet Rahul.</h2><p class="lead">You’re the sales advisor. A customer walks in with a concern. He’s already frustrated.</p><div class="bubble"><span class="label">RAHUL</span>${d[0].q}</div><button class="primary" onclick="decision(0)">WHAT WOULD YOU DO? →</button></div></div>`)}
function decision(i){let x=d[i];render(`${prog(i)}<div><div class="kicker">YOUR MOVE</div><h2>${i===0?'Start with the customer.':x.title}</h2><div class="bubble"><span class="label">CUSTOMER</span>${x.q}</div><div class="choices">${x.a.map(([l,t])=>`<button class="choice" onclick="feedback(${i},'${l}')"><strong>${l}</strong>${t}</button>`).join('')}</div></div>`)}
function feedback(i,l){let x=d[i],good=l===x.best;let msg=good?'You chose to understand before acting. A premium interaction isn’t only about solving the issue. It’s also about how the customer feels while you’re solving it.':'Pause and look again. A helpful response can be a good start—but consider what the customer needs to experience before you move to the next step.';render(`${prog(i)}<div><div class="kicker">${good?'GOOD MOVE':'LOOK AGAIN'}</div><h2>${good?x.phrase:'THE CUSTOMER EXPERIENCE MATTERS.'}</h2><div class="feedback">${msg}</div>${good?`<button class="primary" onclick="concept(${i})">SEE THE PRINCIPLE →</button>`:`<button class="primary" onclick="decision(${i})">TRY ANOTHER RESPONSE</button>`}</div>`)}
function concept(i){let x=d[i];render(`${prog(i)}<div class="concept"><div class="kicker">0${i+1} — ${x.title}</div><h2>${x.phrase}</h2><p class="lead">${x.exp}</p><div class="behaviours">${x.beh.map(v=>`<span>${v}</span>`).join('')}</div><button class="primary" onclick="${i<3?`decision(${i+1})`:'reveal()'}">${i<3?'CONTINUE →':'SEE THE BIGGER PICTURE →'}</button></div>`)}
function reveal(){render(`<div class="reveal"><div class="kicker">THE CUSTOMER JOURNEY</div><h2>YOU JUST EXPERIENCED<br>THE FOUR MOVES.</h2><div class="path"><div><b>UNDERSTAND</b><br><small>Customer Centricity</small></div><div>→</div><div><b>CONNECT</b><br><small>Customer Relation</small></div><div>→</div><div><b>HELP</b><br><small>Solution Orientation</small></div><div>→</div><div><b>STAY</b><br><small>Resolution Management</small></div></div><button class="primary" onclick="premium()">WHAT MAKES IT PREMIUM? →</button></div>`)}
function premium(){render(`<div class="reveal"><div class="kicker">THE BIGGER IDEA</div><h2>WHAT MAKES SERVICE<br>FEEL PREMIUM?</h2><div class="values"><div class="value"><b>DIGNITY</b><p>I feel respected.</p></div><div class="value"><b>PATIENCE</b><p>I feel heard.</p></div><div class="value"><b>WARMTH</b><p>I feel comfortable.</p></div></div><p class="lead"><b>Premium service isn’t about doing more.</b><br>It’s about making the customer feel valued while you help them move forward.</p><button class="primary" onclick="reflection()">REFLECT ON YOUR NEXT CUSTOMER →</button></div>`)}
function reflection(){render(`<div><div class="kicker">YOUR NEXT CUSTOMER</div><h2>Which behaviour will you consciously practise?</h2><div class="reflects"><button class="reflect" onclick="select(this,'UNDERSTAND')"><b>UNDERSTAND</b><p>I’ll listen before assuming.</p></button><button class="reflect" onclick="select(this,'CONNECT')"><b>CONNECT</b><p>I’ll make the customer feel heard.</p></button><button class="reflect" onclick="select(this,'HELP')"><b>HELP</b><p>I’ll look for what can be done.</p></button><button class="reflect" onclick="select(this,'STAY')"><b>STAY</b><p>I’ll take ownership of the next step.</p></button></div><button id="finish" class="primary" disabled onclick="closing()">CHOOSE ONE TO CONTINUE</button></div>`)}
function select(el,v){document.querySelectorAll('.reflect').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');chosen=v;let b=document.getElementById('finish');b.disabled=false;b.textContent='TAKE THIS INTO YOUR NEXT INTERACTION →'}function closing(){render(`<div class="closing"><div class="kicker">YOUR NEXT MOVE</div><h2>${chosen}</h2><p class="lead">One small change can change the entire experience.</p><div class="triad"><span>UNDERSTAND</span><span>CONNECT</span><span>HELP</span><span>STAY</span></div><h2>MAKE THEM<br>FEEL VALUED.</h2><button class="primary" onclick="opening()">RESTART EXPERIENCE</button></div>`)}document.getElementById('restart').onclick=opening;opening();
